name: Deploy to Heroku

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '#deploy')"
    environment: Heroku
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: tiagogouvea/git+https://github.com/ytdl-patched/yt-dlp
        with:
          provider: "heroku"
          app: ${{secrets.HEROKU_APP_NAME}}
          api-key: ${{secrets.HEROKU_API}}
